language: haskell

os:
  - linux
  - osx
  - windows

dist: xenial

addons:
  apt:
    packages:
    - nasm
    - gcc
    - g++
  homebrew:
    packages:
    - ghc
    - nasm
    - gcc

ghc:
  8.4

script: make test
