matrix:
  include:
    - os: linux
      dist: xenial
      language: haskell
      ghc:
        8.4
    - os: osx
      language: generic
    - os: windows
      language: bash
      before_install:
        - choco install -y ghc nasm mingw llvm make
  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - nasm
      - gcc
      - g++
  homebrew:
    packages:
      - ghc
      - nasm
      - gcc

install: true
script: make test
