os:
  - linux
  - osx
  - windows

dist: xenial

addons:
  apt:
    packages:
      ghc
      nasm
      gcc
      g++
  homebrew:
    packages:
      ghc
      nasm
      gcc

ghc:
  8

script: make test
