matrix:
  include:
    - os: linux
      dist: xenial
      language: haskell
      ghc:
        8.4
    - os: osx
  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - nasm
      - gcc
      - g++
  homebrew:
    packages:
      - ghc
      - nasm
      - gcc

install: true
script: make test
