language: haskell

ghc:
  8.4

os:
  - linux
  - osx
  - windows

dist: xenial

addons:
  apt:
    packages:
    - nasm
    - gcc
    - g++
  homebrew:
    packages:
    - nasm
    - gcc

script: make test
