matrix:
  include:
    - os: linux
      dist: xenial
      language: haskell
      ghc:
        8.4
    - os: osx
      language: generic
    - os: windows
      language: bash
  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - nasm
      - gcc
      - g++
  homebrew:
    packages:
      - ghc
      - nasm
      - gcc
  chocolatey:
    packages:
      - ghc
      - nasm
      - mingw
      - llvm

install: true
script: make test
